apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-php-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-php
  template:
    metadata:
      labels:
        app: apache-php
    spec:
      containers:
      - name: apache-php
        image: php:7.4-apache
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/html
          name: html-storage
      volumes:
      - name: html-storage
        persistentVolumeClaim:
          claimName: html-storage-claim