apiVersion: v1
kind: PersistentVolume
metadata:
  name: html-storage
spec:
  capacity:
    storage: 1Gi # adjust the size needed
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/volumes/htmlstorage # replace this with your host directory where you will upload your php app